on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testregistrysal.azurecr.io
        username: ${{ secrets.acr_testregistrysal_username }}
        password: ${{ secrets.acr_testregistrysal_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "https://github.com/atahhadi/applivl/blob/main/dockerfile" -t testregistrysal.azurecr.io/aks101cluster:${{ github.sha }} --label dockerfile-path=https://github.com/atahhadi/applivl/blob/main/dockerfile
        docker push testregistrysal.azurecr.io/aks101cluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks101cluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks101clusteracfe1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks101clusteracfe1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks101clusteracfe1
        container-registry-url: testregistrysal.azurecr.io
        container-registry-username: ${{ secrets.acr_testregistrysal_username }}
        container-registry-password: ${{ secrets.acr_testregistrysal_password }}
        secret-name: aks101clustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks101clusteracfe1
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          testregistrysal.azurecr.io/aks101cluster:${{ github.sha }}
        imagepullsecrets: |
          aks101clustedockerauth
